/**
 * TurboCommons is a general purpose and cross-language library that implements frequently used and generic software development tasks.
 *
 * Website : -> http://www.turbocommons.org
 * License : -> Licensed under the Apache License, Version 2.0. You may not use this file except in compliance with the License.
 * License Url : -> http://www.apache.org/licenses/LICENSE-2.0
 * CopyRight : -> Copyright 2015 Edertone Advanded Solutions (08211 Castellar del Vallès, Barcelona). http://www.edertone.com
 */
 
namespace org_turbocommons_managers {
 
 
    import BaseStrictClass = org_turbocommons_src_main_ts_model.BaseStrictClass;
    
    
    /**
     * Class that allows us to manage validation in an encapsulated way.
     * We can create as many instances as we want, and each instance will store the validation history and global validation state,
     * so we can use this class to validate complex forms or multiple elements globally
     * 
     * @class
     */ 
    export class ValidationManager extends BaseStrictClass{
    
        /** Stores the current state for the applied validations (VALIDATION_OK / VALIDATION_WARNING / VALIDATION_ERROR) */
        public validationStatus:number = 0;
    
    
        /** Stores the list of generated warning or error messages, in the same order as happened. */
        public failedMessagesList:string[] = [];
    
    
        /** Stores the list of failure status codes, in the same order as happened. */
        public failedStatusList:string[] = [];
    
    
        /** Stores the last error message generated by a validation error / warning or empty string if no validation errors happened */
        public lastMessage:String = '';
    
        
        public isString(string:string):boolean {
        
            return true;
        }
    }
}
